=== shdewz/4wc-stream-overlay/4wc-nodecg-bundle/schemas/tournamentTeams.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "tournament teams data",
  "type": "array",
  "default": [
    {
      "team": "Argentina",
      "flag": "AR",
      "seed": 28,
      "players": [
        {
          "id": 9336886,
          "username": "zeta",
          "captain": false
        }
      ]
    }
  ],
  "items": {
    "$id": "#/tournament/team",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "team",
      "flag",
      "seed",
      "players"
    ],
    "properties": {
      "team": {
        "type": "string"
      },
      "flag": {
        "type": "string"
      },
      "seed": {
        "type": "integer"
      },
      "players": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "username",
            "captain"
          ],
          "properties": {
            "id": {
              "type": "integer"
            },
            "username": {
              "type": "string"
            },
            "captain": {
              "type": "boolean"
            }
          }
        }
      }
    }
  }
}

=== shdewz/4wc-stream-overlay/_data/teams.json
[
    {
        "team": "Argentina",
        "flag": "AR",
        "seed": 28,
        "players": [
            {
                "id": 9336886,
                "username": "zeta",
                "captain": false
            },
            {
                "id": 12902737,
                "username": "my angel amuro",
                "captain": false
            },
            {
                "id": 11113067,
                "username": "Tofy",
                "captain": false
            },
            {
                "id": 7329095,
                "username": "Surite",
                "captain": false
            },
            {
                "id": 7119659,
                "username": "Amuro",
                "captain": true
            },
            {
                "id": 4389490,
                "username": "Penguo",
                "captain": false
            },
            {
                "id": 10459580,
                "username": "SMASHCAE",
                "captain": false
            },
            {
                "id": 4700864,
                "username": "Razekon",
                "captain": false
            }
        ]
    },
    {
        "team": "Austria",
        "flag": "AT",
        "seed": 31,
        "players": [
            {
                "id": 4601608,
                "username": "Sparkxei",
                "captain": false
            },
            {
                "id": 21753287,
                "username": "Deshoou",
                "captain": false
            },
            {
                "id": 8369887,
                "username": "fruit cup",
                "captain": false
            },
            {
                "id": 1371974,
                "username": "Teppi",
                "captain": true
            },
            {
                "id": 14506326,
                "username": "Pittinger",
                "captain": false
            },
            {
                "id": 22751439,
                "username": "Ayoukiro",
                "captain": false
            },
            {
                "id": 12807415,
                "username": "[g chan]",
                "captain": false
            },
            {
                "id": 16522589,
                "username": "Teppi Fangirl",
                "captain": false
            }
        ]
    },
    {
        "team": "Australia",
        "flag": "AU",
        "seed": 12,
        "players": [
            {
                "id": 11469447,
                "username": "Arbusion",
                "captain": false
            },
            {
                "id": 10665363,
                "username": "JGLF",
                "captain": true
            },
            {
                "id": 11380644,
                "username": "-sephy",
                "captain": false
            },
            {
                "id": 20963631,
                "username": "Dumb-Andy",
                "captain": false
            },
            {
                "id": 12784319,
                "username": "Fault",
                "captain": false
            },
            {
                "id": 11858763,
                "username": "PoYuTo",
                "captain": false
            },
            {
                "id": 16197865,
                "username": "Supernye",
                "captain": false
            },
            {
                "id": 17720805,
                "username": "hayley",
                "captain": false
            }
        ]
    },
    {
        "team": "Bosnia and Herzegovina",
        "flag": "BA",
        "seed": -1,
        "players": [
            {
                "id": 14658906,
                "username": "dax420",
                "captain": false
            },
            {
                "id": 10270382,
                "username": "Quiligru",
                "captain": false
            },
            {
                "id": 8956749,
                "username": "__Neo",
                "captain": true
            },
            {
                "id": 18017232,
                "username": "my idol goaw",
                "captain": false
            },
            {
                "id": 23143145,
                "username": "V0lcano_",
                "captain": false
            },
            {
                "id": 10854590,
                "username": "Xedon100",
                "captain": false
            },
            {
                "id": 15000287,
                "username": "EmirBiH",
                "captain": false
            }
        ]
    },
    {
        "team": "Belgium",
        "flag": "BE",
        "seed": -1,
        "players": [
            {
                "id": 13717099,
                "username": "uyaz",
                "captain": false
            },
            {
                "id": 11331829,
                "username": "Loriax",
                "captain": false
            },
            {
                "id": 6479616,
                "username": "Mornis",
                "captain": false
            },
            {
                "id": 9184180,
                "username": "iblue",
                "captain": false
            },
            {
                "id": 7078544,
                "username": "Hanori",
                "captain": true
            },
            {
                "id": 4279650,
                "username": "5joshi",
                "captain": false
            },
            {
                "id": 8509247,
                "username": "Vinnie",
                "captain": false
            },
            {
                "id": 11234975,
                "username": "MRB",
                "captain": false
            }
        ]
    },
    {
        "team": "Bulgaria",
        "flag": "BG",
        "seed": -1,
        "players": [
            {
                "id": 7428814,
                "username": "aosora",
                "captain": false
            },
            {
                "id": 4934554,
                "username": "hlanden",
                "captain": true
            },
            {
                "id": 9717848,
                "username": "Ted",
                "captain": false
            },
            {
                "id": 6584220,
                "username": "SynchroHD",
                "captain": false
            },
            {
                "id": 13661543,
                "username": "Sunrize-",
                "captain": false
            },
            {
                "id": 9518027,
                "username": "ivdim",
                "captain": false
            },
            {
                "id": 8170966,
                "username": "Rengmain",
                "captain": false
            },
            {
                "id": 14431596,
                "username": "stimex",
                "captain": false
            }
        ]
    },
    {
        "team": "Brazil",
        "flag": "BR",
        "seed": 8,
        "players": [
            {
                "id": 11317547,
                "username": "Luccachu",
                "captain": false
            },
            {
                "id": 17192419,
                "username": "Lineu",
                "captain": false
            },
            {
                "id": 14592820,
                "username": "Daf0nz",
                "captain": false
            },
            {
                "id": 10997010,
                "username": "TEQUILA BABY",
                "captain": false
            },
            {
                "id": 11984937,
                "username": "RafaelXDP",
                "captain": false
            },
            {
                "id": 15274893,
                "username": "Lirumin",
                "captain": true
            },
            {
                "id": 11461810,
                "username": "kagiura",
                "captain": false
            },
            {
                "id": 12714574,
                "username": "Aphrodi",
                "captain": false
            }
        ]
    },
    {
        "team": "Belarus",
        "flag": "BY",
        "seed": -1,
        "players": [
            {
                "id": 15803625,
                "username": "flover1ss",
                "captain": false
            },
            {
                "id": 6253995,
                "username": "hollaps",
                "captain": false
            },
            {
                "id": 12624101,
                "username": "KFCKiller228",
                "captain": false
            },
            {
                "id": 16006269,
                "username": "ITheQwertyI",
                "captain": false
            },
            {
                "id": 17448980,
                "username": "Neonith",
                "captain": false
            },
            {
                "id": 17604898,
                "username": "Tepe6oHbka",
                "captain": true
            },
            {
                "id": 11134074,
                "username": "Wexxxxxy",
                "captain": false
            },
            {
                "id": 17485776,
                "username": "L1ssak",
                "captain": false
            }
        ]
    },
    {
        "team": "Canada",
        "flag": "CA",
        "seed": 4,
        "players": [
            {
                "id": 16529875,
                "username": "Juan Dario",
                "captain": false
            },
            {
                "id": 2758279,
                "username": "Genryuu Kaiko",
                "captain": false
            },
            {
                "id": 8666950,
                "username": "karate",
                "captain": false
            },
            {
                "id": 2155578,
                "username": "Azer",
                "captain": false
            },
            {
                "id": 11267857,
                "username": "Jimarrah",
